//
//  Localizable.h
//  box-Authorizer
//
//  Created by Yu Huang on 2018/7/17.
//  Copyright © 2018年 2se. All rights reserved.
//

#ifndef Localizable_h
#define Localizable_h

#define LimitTimes  NSLocalizedString(@"LimitTimes", nil)
#define AccountPasswordHour  NSLocalizedString(@"AccountPasswordHour", nil)
#define Limit  NSLocalizedString(@"Limit", nil)
#define LimitAlertAffirm  NSLocalizedString(@"LimitAlertAffirm", nil)
#define LimitAlertTitle  NSLocalizedString(@"LimitAlertTitle", nil)
#define LimitAlertContent  NSLocalizedString(@"LimitAlertContent", nil)
#define viewLog  NSLocalizedString(@"viewLog", nil)
#define ApprovalBusinessSucceed  NSLocalizedString(@"ApprovalBusinessSucceed", nil)
#define ApprovalBusinessFail  NSLocalizedString(@"ApprovalBusinessFail", nil)
#define Reason  NSLocalizedString(@"Reason", nil)
#define RefuseApproval  NSLocalizedString(@"RefuseApproval", nil)
#define RefuseApprovalInfo  NSLocalizedString(@"RefuseApprovalInfo", nil)
#define Submit  NSLocalizedString(@"Submit", nil)
#define RefuseApprovalPlacehode  NSLocalizedString(@"RefuseApprovalPlacehode", nil)
#define Cancel  NSLocalizedString(@"Cancel", nil)
#define RefuseTransfer  NSLocalizedString(@"RefuseTransfer", nil)
#define InitAccountVCTitle  NSLocalizedString(@"InitAccountVCTitle", nil)
#define PerfectInformationVCLaber  NSLocalizedString(@"PerfectInformationVCLaber", nil)
#define PerfectInformationVCSubLaber  NSLocalizedString(@"PerfectInformationVCSubLaber", nil)
#define ScanCodeVCTitle  NSLocalizedString(@"ScanCodeVCTitle", nil)
#define PerfectInformationVCTorchlight  NSLocalizedString(@"PerfectInformationVCTorchlight", nil)
#define PerfectInformationVCTorchheight  NSLocalizedString(@"PerfectInformationVCTorchheight", nil)
#define PerfectInformationVCScanResult  NSLocalizedString(@"PerfectInformationVCScanResult", nil)
#define PerfectInformationVCErrorCode  NSLocalizedString(@"PerfectInformationVCErrorCode", nil)
#define Handing  NSLocalizedString(@"Handing", nil)
#define PerfectInformationVCTitle  NSLocalizedString(@"PerfectInformationVCTitle", nil)
#define PerfectInformationVCNameText  NSLocalizedString(@"PerfectInformationVCNameText", nil)
#define PerfectInformationVCPasswordText  NSLocalizedString(@"PerfectInformationVCPasswordText", nil)
#define PerfectInformationVCVerifyText  NSLocalizedString(@"PerfectInformationVCVerifyText", nil)
#define PerfectInformationVCAlert  NSLocalizedString(@"PerfectInformationVCAlert", nil)
#define Submit  NSLocalizedString(@"Submit", nil)
#define PerfectInformationVCAlertOne  NSLocalizedString(@"PerfectInformationVCAlertOne", nil)
#define PerfectInformationVCAlertTwo  NSLocalizedString(@"PerfectInformationVCAlertTwo", nil)
#define PerfectInformationVCAlertThree  NSLocalizedString(@"PerfectInformationVCAlertThree", nil)
#define PerfectInformationVCCheckPwd  NSLocalizedString(@"PerfectInformationVCCheckPwd", nil)
#define SubmissionCompletion  NSLocalizedString(@"SubmissionCompletion", nil)
#define BackupVCContentlab  NSLocalizedString(@"BackupVCContentlab", nil)
#define BackupVCbackupButton  NSLocalizedString(@"BackupVCbackupButton", nil)
#define BackupVCSVProgressOne  NSLocalizedString(@"BackupVCSVProgressOne", nil)
#define BackupVCWSProgressTwo  NSLocalizedString(@"BackupVCWSProgressTwo", nil)
#define ServiceStartAwaitBtn  NSLocalizedString(@"ServiceStartAwaitBtn", nil)
#define NextStep  NSLocalizedString(@"NextStep", nil)
#define AwaitBackupVCContentLabText  NSLocalizedString(@"AwaitBackupVCContentLabText", nil)
#define AwaitBackupVCContentLabStatusText  NSLocalizedString(@"AwaitBackupVCContentLabStatusText", nil)
#define AwaitBackupVnextButtonTitle  NSLocalizedString(@"AwaitBackupVnextButtonTitle", nil)
#define AwaitBackupVCContentLabNextText  NSLocalizedString(@"AwaitBackupVCContentLabNextText", nil)
#define BlueToothListVCTitle  NSLocalizedString(@"BlueToothListVCTitle", nil)
#define GenerateContractVCTitle  NSLocalizedString(@"GenerateContractVCTitle", nil)
#define GenerateContractVCScanLab  NSLocalizedString(@"GenerateContractVCScanLab", nil)
#define GenerateContractVCAccountCopyBtn  NSLocalizedString(@"GenerateContractVCAccountCopyBtn", nil)
#define GenerateContractVCAccountSaveBtn  NSLocalizedString(@"GenerateContractVCAccountSaveBtn", nil)
#define GenerateContractVCscanTwoLab  NSLocalizedString(@"GenerateContractVCscanTwoLab", nil)
#define GenerateContractVCprivateBtn  NSLocalizedString(@"GenerateContractVCprivateBtn", nil)
#define GenerateContractVserviceStartBtn  NSLocalizedString(@"GenerateContractVserviceStartBtn", nil)
#define CopyAddressSucceed  NSLocalizedString(@"CopyAddressSucceed", nil)
#define SaveFailure  NSLocalizedString(@"SaveFailure", nil)
#define SavePicturesucceed  NSLocalizedString(@"SavePicturesucceed", nil)
#define PasswordWaitingForCheck  NSLocalizedString(@"PasswordWaitingForCheck", nil)
#define ServiceException  NSLocalizedString(@"ServiceException", nil)
#define CheckPasswordFailed  NSLocalizedString(@"CheckPasswordFailed", nil)
#define Refresh  NSLocalizedString(@"Refresh", nil)
#define ServiceStartTitle  NSLocalizedString(@"ServiceStartTitle", nil)
#define ServiceStartLaunchUnstart  NSLocalizedString(@"ServiceStartLaunchUnstart", nil)
#define ServiceStartLaunchState  NSLocalizedString(@"ServiceStartLaunchState", nil)
#define ServiceStartLaunchStateSecceed  NSLocalizedString(@"ServiceStartLaunchStateSecceed", nil)
#define ServiceStartPassword  NSLocalizedString(@"ServiceStartPassword", nil)
#define ServiceStartRepassword  NSLocalizedString(@"ServiceStartRepassword", nil)
#define ServiceStartCommitStart  NSLocalizedString(@"ServiceStartCommitStart", nil)
#define ServiceStartCommitStartUse  NSLocalizedString(@"ServiceStartCommitStartUse", nil)
#define ServiceStateTitle  NSLocalizedString(@"ServiceStateTitle", nil)
#define ServiceStateDetail  NSLocalizedString(@"ServiceStateDetail", nil)
#define ServiceStartAleartOne  NSLocalizedString(@"ServiceStartAleartOne", nil)
#define ServiceStartAleartTwo  NSLocalizedString(@"ServiceStartAleartTwo", nil)
#define ServiceStartPwdTitle  NSLocalizedString(@"ServiceStartPwdTitle", nil)
#define StartupServiceFailed  NSLocalizedString(@"StartupServiceFailed", nil)
#define AllPrivateAppStartedService  NSLocalizedString(@"AllPrivateAppStartedService", nil)
#define BackupViewBackupLab  NSLocalizedString(@"BackupViewBackupLab", nil)
#define BackupViewBackupText  NSLocalizedString(@"BackupViewBackupText", nil)
#define BackupViewAlertLab  NSLocalizedString(@"BackupViewAlertLab", nil)
#define BackupViewCheckPwd  NSLocalizedString(@"BackupViewCheckPwd", nil)
#define Confirm  NSLocalizedString(@"Confirm", nil)
#define ConnectionSuccess  NSLocalizedString(@"ConnectionSuccess", nil)
#define Unconnected  NSLocalizedString(@"Unconnected", nil)
#define PrintAlertViewPrinting  NSLocalizedString(@"PrintAlertViewPrinting", nil)
#define PrintImmediately  NSLocalizedString(@"PrintImmediately", nil)
#define Reprint  NSLocalizedString(@"Reprint", nil)
#define PrintSuccessfully  NSLocalizedString(@"PrintSuccessfully", nil)
#define PrintAlertViewAlertLabText  NSLocalizedString(@"PrintAlertViewAlertLabText", nil)
#define GenerateContract  NSLocalizedString(@"GenerateContract", nil)
#define PrintAlertViewBTPrinting  NSLocalizedString(@"PrintAlertViewBTPrinting", nil)
#define PrintAlertViewBTConnectFail  NSLocalizedString(@"PrintAlertViewBTConnectFail", nil)

#define PrivatePasswordbackupLab  NSLocalizedString(@"PrivatePasswordbackupLab", nil)
#define PrivatePasswordComfirm  NSLocalizedString(@"PrivatePasswordComfirm", nil)
#define PrivatePasswordPasswordTfPlaceholder  NSLocalizedString(@"PrivatePasswordPasswordTfPlaceholder", nil)
#define HomepageMidOneLabStop  NSLocalizedString(@"HomepageMidOneLabStop", nil)
#define HomepageMidOneLabStart  NSLocalizedString(@"HomepageMidOneLabStart", nil)
#define HomepageMidOneLabDetailStop  NSLocalizedString(@"HomepageMidOneLabDetailStop", nil)
#define HomepageMidOneLabDetailStart  NSLocalizedString(@"HomepageMidOneLabDetailStart", nil)
#define HomepageMidOneLabDetailError  NSLocalizedString(@"HomepageMidOneLabDetailError", nil)
#define HomepageMidTwoLab  NSLocalizedString(@"HomepageMidTwoLab", nil)
#define HomepageMidThreeLab  NSLocalizedString(@"HomepageMidThreeLab", nil)
#define HomepageMidFourLab  NSLocalizedString(@"HomepageMidFourLab", nil)
#define HomepageMidFourDetailLab  NSLocalizedString(@"HomepageMidFourDetailLab", nil)
#define HomepageFootTitle  NSLocalizedString(@"HomepageFootTitle", nil)
#define HomepageTitle  NSLocalizedString(@"HomepageTitle", nil)
#define HomepageNoApproval  NSLocalizedString(@"HomepageNoApproval", nil)
#define HomepageNoCurrency  NSLocalizedString(@"HomepageNoCurrency", nil)
#define OpenApp  NSLocalizedString(@"OpenApp", nil)
#define NoDynamic  NSLocalizedString(@"NoDynamic", nil)
#define WaitCheck  NSLocalizedString(@"WaitCheck", nil)
#define StartedService  NSLocalizedString(@"StartedService", nil)
#define StoppedService  NSLocalizedString(@"StoppedService", nil)
#define NotConnected  NSLocalizedString(@"NotConnected", nil)
#define AssetOverview  NSLocalizedString(@"AssetOverview", nil)
#define ServerAddress  NSLocalizedString(@"ServerAddress", nil)
#define Language  NSLocalizedString(@"Language", nil)
#define AboutBOX  NSLocalizedString(@"AboutBOX", nil)
#define HomepageSeverStartLaber  NSLocalizedString(@"HomepageSeverStartLaber", nil)
#define HomepageSeverStopLaber  NSLocalizedString(@"HomepageSeverStopLaber", nil)
#define HomepageSeverStartButton  NSLocalizedString(@"HomepageSeverStartButton", nil)
#define HomepageSeverStopButton  NSLocalizedString(@"HomepageSeverStopButton", nil)

#define AddCurrencyVCTitle  NSLocalizedString(@"AddCurrencyVCTitle", nil)
#define AddCurrencyVCCurrencyNameTf  NSLocalizedString(@"AddCurrencyVCCurrencyNameTf", nil)
#define AddCurrencyVCCurrencyAdressTf  NSLocalizedString(@"AddCurrencyVCCurrencyAdressTf", nil)
#define AddCurrencyVCaccuracyTf  NSLocalizedString(@"AddCurrencyVCaccuracyTf", nil)
#define AddCurrencyVCCormfirmButton  NSLocalizedString(@"AddCurrencyVCCormfirmButton", nil)
#define AddCurrencyVCAddSuccess  NSLocalizedString(@"AddCurrencyVCAddSuccess", nil)
#define OpenAccount  NSLocalizedString(@"OpenAccount", nil)
#define Cancel  NSLocalizedString(@"Cancel", nil)
#define Affirm  NSLocalizedString(@"Affirm", nil)
#define delete  NSLocalizedString(@"delete", nil)
#define SureToDelete  NSLocalizedString(@"SureToDelete", nil)
#define ScanAdressVCTitle  NSLocalizedString(@"ScanAdressVCTitle", nil)
#define ScanAdressVCScanLab  NSLocalizedString(@"ScanAdressVCScanLab", nil)
#define ScanAdressVCDetailLab  NSLocalizedString(@"ScanAdressVCDetailLab", nil)
#define ScanAdressVCAuthorizeBtn  NSLocalizedString(@"ScanAdressVCAuthorizeBtn", nil)
#define ScanAdressVCAleartLab  NSLocalizedString(@"ScanAdressVCAleartLab", nil)
#define ScanAdressVCIknown  NSLocalizedString(@"ScanAdressVCIknown", nil)
#define ScanAdressVCAlertMessage  NSLocalizedString(@"ScanAdressVCAlertMessage", nil)
#define ApprovalBusinessDetailVCAgreeApprovalBtn  NSLocalizedString(@"ApprovalBusinessDetailVCAgreeApprovalBtn", nil)
#define ApprovalBusinessDetailVCRefuseApprovalBtn  NSLocalizedString(@"ApprovalBusinessDetailVCRefuseApprovalBtn", nil)
#define ApprovalBusinessDetailApprovaling  NSLocalizedString(@"ApprovalBusinessDetailApprovaling", nil)
#define ApprovalBusinessDetailSucceed  NSLocalizedString(@"ApprovalBusinessDetailSucceed", nil)
#define ApprovalBusinessDetailFail  NSLocalizedString(@"ApprovalBusinessDetailFail", nil)
#define ApprovalBusinessDetailAwait  NSLocalizedString(@"ApprovalBusinessDetailAwait", nil)
#define ApprovalBusinessDetailAgreen  NSLocalizedString(@"ApprovalBusinessDetailAgreen", nil)
#define IllegalApprovalFlow  NSLocalizedString(@"IllegalApprovalFlow", nil)
#define ApprovalBusinessVCTitle  NSLocalizedString(@"ApprovalBusinessVCTitle", nil)
#define ApprovalBusinessVCSegmentedTitleOne  NSLocalizedString(@"ApprovalBusinessVCSegmentedTitleOne", nil)
#define ApprovalBusinessVCSegmentedTitleTwo  NSLocalizedString(@"ApprovalBusinessVCSegmentedTitleTwo", nil)
#define ApprovalAwaitBusiness  NSLocalizedString(@"ApprovalAwaitBusiness", nil)
#define ApprovalingBusiness  NSLocalizedString(@"ApprovalingBusiness", nil)
#define ApprovalSucceedBusiness  NSLocalizedString(@"ApprovalSucceedBusiness", nil)
#define ApprovalFailBusiness  NSLocalizedString(@"ApprovalFailBusiness", nil)
#define CurrencyAccountTableViewCellAddCurrency  NSLocalizedString(@"CurrencyAccountTableViewCellAddCurrency", nil)
#define ApprovalMenber  NSLocalizedString(@"ApprovalMenber", nil)
#define ApprovalMenberAmount  NSLocalizedString(@"ApprovalMenberAmount", nil)
#define CurrentVersion  NSLocalizedString(@"CurrentVersion", nil)
#define SimplifiedChinese  NSLocalizedString(@"SimplifiedChinese", nil)
#define ModifyServerAddressVCTitle  NSLocalizedString(@"ModifyServerAddressVCTitle", nil)
#define ModifyServerAddressVCAddress  NSLocalizedString(@"ModifyServerAddressVCAddress", nil)
#define ModifyServerAddressVCInfo  NSLocalizedString(@"ModifyServerAddressVCInfo", nil)
#define ModifyServerAddressVCVerifyBtn  NSLocalizedString(@"ModifyServerAddressVCVerifyBtn", nil)
#define ModifyServerAddressVCAleartSucceed  NSLocalizedString(@"ModifyServerAddressVCAleartSucceed", nil)
#define Detailed  NSLocalizedString(@"Detailed", nil)
#define TransferRecordTableViewCellTransferingAwait  NSLocalizedString(@"TransferRecordTableViewCellTransferingAwait", nil)
#define TransferRecordTableViewCellTransfering  NSLocalizedString(@"TransferRecordTableViewCellTransfering", nil)
#define TransferRecordTableViewCellTransferStateSucceed  NSLocalizedString(@"TransferRecordTableViewCellTransferStateSucceed", nil)
#define TransferRecordTableViewCellTransferStateSucceedTransfing  NSLocalizedString(@"TransferRecordTableViewCellTransferStateSucceedTransfing", nil)
#define TransferRecordTableViewCellTransferStateFail  NSLocalizedString(@"TransferRecordTableViewCellTransferStateFail", nil)
#define TransferRecordTableViewCellRecharge  NSLocalizedString(@"TransferRecordTableViewCellRecharge", nil)
#define TransferRecordTableViewCellTransferFail  NSLocalizedString(@"TransferRecordTableViewCellTransferFail", nil)

#define ApprovalBusinessCancel  NSLocalizedString(@"ApprovalBusinessCancel", nil)
#define SystemApprovalSucceed  NSLocalizedString(@"SystemApprovalSucceed", nil)
#define SystemApprovalFail  NSLocalizedString(@"SystemApprovalFail", nil)
#define ApprovalCancel  NSLocalizedString(@"ApprovalCancel", nil)
#define SureToDeleteSection  NSLocalizedString(@"SureToDeleteSection", nil)
#define ApprovalCreate  NSLocalizedString(@"ApprovalCreate", nil)





#endif /* Localizable_h */
